---
title: Estimating confidence intervals for gravel bed surface
  grain size distributions - analysis code
author:
- Brett C. Eaton$^{1,*}$, R. Dan Moore$^1$, and Lucy G. MacKenzie$^1$
- $^1$ Department of Geography, The University of British Columbia
- $^*$ Corresponding Author (brett.eaton@ubc.ca)
date: "May 24, 2019"
output:
  html_document:
    df_print: paged
---
#Set up the working environment

```{r, echo=TRUE} 

rm(list = ls())

library(reshape2)
library(xtable)
library(ggplot2)

# RUN IF YOU HAVE NOT INSTALLED THE GSDtools PACKAGE
#  library(devtools)
#  install_github("bceaton/GSDtools")

library(GSDtools)

load("GSD_data.RData")  #load the dataset
load("GSD_simulations.RData")  #load the first dataset in the list

```

#Analysis in the paper
The following code chunks contain the commands used to create all the figures in the paper, using the data files provided. 

```{r} 
set.seed(8)
d.demo = sort(sample(all1.data$D, size = 100))
cfd.demo = (seq_along(d.demo)-1)/length(d.demo)

```

```{r,"fig1"} 

p = 0.5
n = 100
k = 40:60
barplot(dbinom(k,n,p),
        names = k,
        xlab = "No. of successes",
        ylab = "probability",
        ylim = c(0,0.1))
head.coverage = sum(dbinom(k,n,p))

```

```{r, "fig2"}

n = 100
p = 0.50
firstINT = QuantBD(n, p)
up = firstINT$interval[2]
lo = firstINT$interval[1]


par(mar=c(4,5,1,1))
par(oma = c(0,0,0,0))
par(mfrow = c(2,2))

plot(MakeCFD(all1.data$D),
     type = "l",
     col = rgb(0,0,0,0.25),
     log = "x",
     lwd = 4,
     lty =1,
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer")
text(x = 7, y = 0.02, labels = "(a)")
abline(v = median(all1.data$D), lty = 2, lwd = 2, col=rgb(0,0,0,0.25))
abline(h = 0.5, lty = 3, lwd = 2, col=rgb(0,0,0,0.25))
legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1),
       legend = c("population", "50th Percentile", expression(D[50])),
       lty = c(1,3,2),
       lwd = c(4,2,2),
       col = c(rgb(0,0,0,0.25))
)

plot(d.demo, cfd.demo,
     type ="b",
     pch = 21,
     log = "x",
     col = rgb(0,0,1,0.35),
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer"
     )
lines(MakeCFD(all1.data$D),
      col = rgb(0,0,0,0.25),
      lwd = 4,
      lty =1)
lines( c(d.demo[n/2], d.demo[n/2]), c(-0.1, 1.1), lty = 1,col = rgb(0,0,1))
text(x = 7, y = 0.02, labels = "(b)")
abline(v = median(all1.data$D), lty = 2, lwd = 2, col=rgb(0,0,0,0.25))
abline(h = 0.5, lty = 3, lwd = 2, col=rgb(0,0,0,0.25))

legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1,1),
       legend = c("sample", expression(d[50])),
       lty = c(NA,1),
       lwd = c(NA,1),
       pch = c(21,NA),
       col = c(rgb(0,0,1,0.35),rgb(0,0,1))
)

plot(d.demo, cfd.demo,
     type ="b",
     pch = 21,
     #cex = 0.75,
     log = "x",
     col = rgb(0,0,1,0.35),
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer"
     )
points(c(d.demo[up], d.demo[lo]),c(up/n, lo/n), pch = 19, col = "red")
arrows(0.4, up/n, x1 = d.demo[up], y1 = up/n, length = 0.15, angle = 30,
       code = 2, lwd = 2)
arrows(0.4, lo/n, x1 = d.demo[lo], y1 = lo/n, length = 0.15, angle = 30,
       code = 2, lwd = 2)

abline(v = median(all1.data$D), lty = 2, lwd = 2, col=rgb(0,0,0,0.25))
polygon(x = c(0.4,0.4,10,10), y = c(0.4,0.6,0.6,0.4),
        lty = 0,
        col = rgb(0,0,0,0.2))
text(x = 7, y = 0.02, labels = "(c)")
legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1,1),
       legend = c("reference points", "percentile C.I."),
       lty = c(NA,1),
       lwd = c(NA,10),
       pch = c(19,NA),
       col = c(rgb(1,0,0),rgb(0,0,0,0.2))
)

plot(d.demo, cfd.demo,
     type ="b",
     pch = 21,
     log = "x",
     col = rgb(0,0,1,0.35),
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer"
     )
arrows(d.demo[up], up/n,
       x1 = d.demo[up], y1 = 0,
       length = 0.15,
       angle = 30,
       code = 2,
       lwd =2)
arrows(d.demo[lo], lo/n,
       x1 = d.demo[lo], y1 = 0,
       length = 0.15,
       angle = 30,
       code = 2,
       lwd=2)
points(c(d.demo[up], d.demo[lo]),c(up/n, lo/n), pch = 19, col = "red")
abline(v = median(all1.data$D), lty = 2,  lwd = 2, col=rgb(0,0,0,0.25))
polygon(x = c(d.demo[up],d.demo[up],d.demo[lo],d.demo[lo]), y = c(-0.2,1.2,1.2,-0.2),
        lty = 0,
        col = rgb(0,0,0,0.2))
text(x = 7, y = 0.02, labels = "(d)")
legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1,1),
       #box.lty = 0,
       legend = c("reference points", "grain size C.I."),
       lty = c(NA,1),
       lwd = c(NA,10),
       pch = c(19,NA),
       col = c(rgb(1,0,0),rgb(0,0,0,0.2))
)

```

```{r, "fig3"}
set.seed(8)
d.demo = sort(sample(all1.data$D, size = 200))
cfd.demo = (seq_along(d.demo)-1)/length(d.demo)

# calculate the binomial limits for specified values n and p
n = 200
p = 0.84
firstINT = QuantBD(n, p)

#the exact binomial confidence interval, based on measurements
l = firstINT$interval[1]
u = firstINT$interval[2]
dl = d.demo[l]
du = d.demo[u]

#the equal tail approximation applied to the complete dataset
le = firstINT$equaltail[1]
ue = firstINT$equaltail[2]
dle = as.numeric(approx(x=seq_along(d.demo), y = d.demo, xout = le )[2])
due = as.numeric(approx(x=seq_along(d.demo), y = d.demo, xout = ue )[2])

#the equal tail approximation applied to the binned data
d.binned = MakeCFD(d.demo)
dlb = 2^as.numeric(approx(x=d.binned$probs, y = log2(d.binned$size), xout = le/200 )[2])
dub = 2^as.numeric(approx(x=d.binned$probs, y = log2(d.binned$size), xout = ue/200 )[2])
dest = 2^as.numeric(approx(x=d.binned$probs, y = log2(d.binned$size), xout = 0.84 )[2])

par(mar=c(4,5,1,1))
par(oma = c(0,0,0,0))
par(mfrow = c(1,2))

plot(MakeCFD(d.demo),
     type ="b",
     pch = 20,
     lwd =2,
     #cex = 0.75,
     log = "x",
     col = rgb(1,0,0,0.75),
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer"
     )

points(d.demo, cfd.demo,
     pch = 21,
     col = rgb(0,0,1,0.35))

tmp = WolmanCI(MakeCFD(d.demo), n = 200, P = c(84))
abline(v = tmp[[2]],
       lty = 2,
       lwd = 2,
       col=rgb(1,0,0,0.75))
abline(v = d.demo[2*84],
       lty = 1,
       lwd = 2,
       col=rgb(0,0,1))
legend("topleft",
       inset = 0.03,
       cex = 0.75,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c("original data",
                  "binned data",
                  expression(d[84]~original),
                  expression(d[84]~binned)
                  ),
       lty = c(NA,1,1,2,1),
       lwd = c(NA,2,2,2,10),
       pch = c(21,20,NA,NA,NA),
       col = c(rgb(0,0,1,0.35),
               rgb(1,0,0,0.75),
               rgb(0,0,1),
               rgb(1,0,0,0.75),
               rgb(0,0,0,0.2))
)
text(x = 7, y = 0.02, labels = "(a)")

plot(MakeCFD(d.demo),
     type ="b",
     pch = 20,
     lwd =2,
     #cex = 0.75,
     log = "x",
     col = rgb(1,0,0,0.75),
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer"
     )
qtmp = QuantBD(200, 0.84)
lines(x = c(0.4, tmp[[4]]),
      y = c(qtmp$equaltail[2]/200,qtmp$equaltail[2]/200),
      lty = 2,
      lwd = 1,
      col = rgb(0,0,0, 0.5))
lines(x = c(0.4, tmp[[3]]),
      y = c(qtmp$equaltail[1]/200,qtmp$equaltail[1]/200),
      lty = 2,
      lwd = 1,
      col = rgb(0,0,0,0.5))

polygon(x = c(tmp[[4]],tmp[[4]],tmp[[3]],tmp[[3]]), y = c(-0.2,1.2,1.2,-0.2),
        lty = 0,
        col = rgb(0,0,0,0.2))
legend("bottomright",
       inset = 0.03,
       cex = 0.75,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c("binned data",
                  "percentile C.I.",
                  "grain size C.I."),
       lty = c(1,2,1),
       lwd = c(2,1,10),
       pch = c(20,NA,NA),
       col = c(rgb(1,0,0,0.75),
               rgb(0,0,0,0.5),
               rgb(0,0,0,0.2))
)
text(x = 7, y = 0.94, labels = "(b)")

```

```{r, "Fig4"}

k = 150:190
pr = dbinom(k, n, p)
df = data.frame(k, pr)

# find upper and lower limits and output coverage probability.
qci = QuantBD(n, p)
lu_exact = qci$interval
p_c = qci$coverage


df$bar_col = ifelse(df$k >= lu_exact[1] & df$k < lu_exact[2], "C.I.", "tail")

# using ggplot since barplots in base graphics are a bit awkward
par(mar=c(4,4,1,1))
par(oma = c(0,0,0,0))

ggplot(df, aes(x = k, y = pr)) +
  geom_col(aes(fill = bar_col), na.rm = T) +
  scale_x_continuous(limits = c(150, 190)) +
  scale_y_continuous(limits = c(0, 0.08)) +
  scale_fill_manual(values = c("darkgrey", "lightgrey"), name = "") +
  labs(x = expression(italic(k)),
       y = expression(italic(P[r](k, 200, 0.84)))) +
  theme_bw() +
  theme(axis.text = element_text(size = 12)) +
  theme(axis.title = element_text(size = 12)) +
  geom_vline(xintercept = firstINT$equaltail+0.5, lty = 2)

```

```{r, "Fig5"}

par(mar=c(4,5,1,1))
par(oma = c(0,0,0,0))
par(mfrow = c(1,2))

plot(MakeCFD(all1.data$D, increment = 0.25),
     type = "l",
     col = rgb(0,0,0,0.25),
     log = "x",
     lwd = 4,
     lty =1,
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer")

for(i in seq(1,25)){
  points(x = sample.100[,i], y = seq(0, 99)/100,
         pch = 19,
         col = rgb(1,0,0,0.1))
}
lines(x = ci100$upper, y = ci100$probs,
      col = rgb(0,0,0,1),
      lwd = 2,
      lty = 2)
lines(x = ci100$lower, y = ci100$probs,
      col = rgb(0,0,0,1),
      lwd = 2,
      lty = 2)

legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c("95% C.I.", "100-stone samples"),
       lty = c(2,NA),
       pch = c(NA, 19),
       lwd = c(2,NA),
       col = c(rgb(0,0,0),rgb(1,0,0))
)
text(x = 7, y = 0.02, labels = "(a)")

# now with 400 stones sampled
plot(MakeCFD(all1.data$D, increment = 0.25),
     type = "l",
     col = rgb(0,0,0,0.25),
     log = "x",
     lwd = 4,
     lty =1,
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer")

for(i in seq(1,25)){
  points(x = sample.400[,i], y = seq(0, 399)/400,
         pch = 19,
         col = rgb(0,0,1,0.1))
}
lines(x = ci400$upper, y = ci400$probs,
      col = rgb(0,0,0,1),
      lwd = 2,
      lty = 2)
lines(x = ci400$lower, y = ci400$probs,
      col = rgb(0,0,0,1),
      lwd = 2,
      lty = 2)

legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c("95% C.I.", "400-stone samples"),
       lty = c(2,NA),
       pch = c(NA, 19),
       lwd = c(2,NA),
       col = c(rgb(0,0,0),rgb(0,0,1))
)
text(x = 7, y = 0.02, labels = "(b)")

```

```{r, "Fig6"}

par(mar=c(4,5,1,1))
par(oma = c(0,0,0,0))

plot(MakeCFD(all1.data$D, increment = 0.25),
     type = "l",
     col = rgb(0,0,0,0.25),
     log = "x",
     lwd = 4,
     lty =1,
     ylim = c(0, 1),
     xlim = c(0.5, 8),
     xlab = "grain size (mm)",
     ylab = "proportion finer")
lines(x = ci100$upper, y = ci100$probs,
      col = rgb(1,0,0,1),
      lwd = 2,
      lty = 2)
lines(x = ci100$lower, y = ci100$probs,
      col = rgb(1,0,0,1),
      lwd = 2,
      lty = 2)
points(x = bootstrap100$upper, y = bootstrap100$qntls,
       pch = 19,
       cex = 0.7,
       col = rgb(1,0,0,1))
points(x = bootstrap100$lower, y = bootstrap100$qntls,
       pch = 19,
       cex = 0.7,
       col = rgb(1,0,0,1))
lines(x = ci400$upper, y = ci400$probs,
      col = rgb(0,0,1,1),
      lwd = 2,
      lty = 2)
lines(x = ci400$lower, y = ci400$probs,
      col = rgb(0,0,1,1),
      lwd = 2,
      lty = 2)
points(x = bootstrap400$upper, y = bootstrap400$qntls,
       pch = 19,
       cex = 0.7,
       col = rgb(0,0,1,1))
points(x = bootstrap400$lower, y = bootstrap400$qntls,
       pch = 19,
       cex = 0.7,
       col = rgb(0,0,1,1))
legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c("population",
                  "bootstrap CI (n = 100)",
                  "binomial CI (n = 100)",
                  "bootstrap CI (n = 400)",
                  "binomial CI (n = 100)"),
       lty = c(1,NA,2,NA, 2),
       pch = c(NA, 19, NA, 19, NA),
       lwd = c(4,NA,2,NA,2),
       col = c(rgb(0,0,0,0.25),
               rgb(1,0,0),
               rgb(1,0,0),
               rgb(0,0,1),
               rgb(0,0,1))
)


X = log2(c(bootstrap100$lower, bootstrap100$upper))
Y = log2(c(ci100$lower, ci100$upper))
ss.total = sum((Y - mean(Y, na.rm = T))^2, na.rm = T)
ss.err = sum((X - Y)^2, na.rm = T)
R2.100 = 1 - ss.err/ss.total
rmse.100 = sqrt(ss.err/sum(!is.na(Y)))
bias.100 = mean((X - Y), na.rm = T)

X = log2(c(bootstrap400$lower, bootstrap400$upper))
Y = log2(c(ci400$lower, ci400$upper))
ss.total = sum((Y - mean(Y))^2)
ss.err = sum((X - Y)^2)
R2.400 = 1 - ss.err/ss.total
rmse.400 = sqrt(ss.err/sum(!is.na(Y)))
bias.400 = mean((X - Y), na.rm = T)

X = log2(c(simstrap100$lower, simstrap100$upper,simstrap400$lower, simstrap400$upper))
Y = log2(c(sim100$lower, sim100$upper,sim400$lower, sim400$upper))
ss.total = sum((Y - mean(Y, na.rm = T))^2, na.rm = T)
ss.err = sum((X - Y)^2, na.rm = T)
R2.sim = 1 - ss.err/ss.total
rmse.sim = sqrt(ss.err/sum(!is.na(Y)))
bias.sim = mean((X - Y), na.rm = T)


```

```{r, "Fig7"}

par(mfcol=c(1,2))
par(mar=c(4,4,0.5,0.5))
par(oma = c(0,0,0,0))

#Willow Creek analysis
#CompareGSDs(cfdpool, cfdrun, 400, 400, alpha = 0.05)
#above shows diff signif for finer than D30 and coarser than D65

#CompareGSDs(cfdpool, cfdrun, 400, 400, alpha = 0.01)
#above shows diff only signif for finer than D30

#N. St. Vrain Creek analysls
#CompareGSDs(cfdpool4, cfdrun4, 400, 400, alpha = 0.05)
#shows all different except for D15 and finer,and D80 D84

#CompareGSDs(cfdpool4, cfdrun4, 400, 400, alpha = 0.01)
#shows all different except for D15 and finer

plot(cfdpool$size, cfdpool$probs,
     type ="p",
     pch = 19,
     log = "x",
     col = "blue",
     ylim = c(0, 1),
     xlim = c(2,400),
     xlab = "grain size (mm)",
     ylab = "Proportion Finer"
     )
polygon(polypool,
        col=rgb(0, 0, 1,0.3),
        lty = 0)
abline(v = c(22.6), lty = 2, col = rgb(1,0,0))
text(x = 300, y = 0.02, labels = "(a)")

points(cfdbar$size, cfdbar$probs, pch = 19, col = rgb(0.5,0,1))
polygon(polybar,
        col=rgb(0.5, 0, 1,0.3),
        lty = 0)

points(cfdrun$size, cfdrun$probs, pch = 19, col = rgb(1,0.25,0))
polygon(polyrun,
        col=rgb(1, 0.25, 0,0.3),
        lty = 0)

plot(cfdpool4$size, cfdpool4$probs,
     type ="p",
     yaxt = "n",
     pch = 19,
     log = "x",
     col = "blue",
     ylim = c(0, 1),
     xlim = c(2,400),
     xlab = "grain size (mm)",
     ylab = " "
     )
polygon(polypool4,
        col=rgb(0, 0, 1,0.3),
        lty = 0)
abline(v = c(22.6), lty = 2, col = rgb(1,0,0))

text(x = 300, y = 0.02, labels = "(b)")

points(cfdbar4$size, cfdbar4$probs, pch = 19, col = rgb(0.5,0,1))
polygon(polybar4,
        col=rgb(0.5, 0, 1,0.3),
        lty = 0)

points(cfdrun4$size, cfdrun4$probs, pch = 19, col = rgb(1,0.25,0))
polygon(polyrun4,
        col=rgb(1, 0.25, 0,0.3),
        lty = 0)
legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c("pool", "exposed bar", "run/riffle", "22.6 mm"),
       lty = c(0,0,0,2),
       pch = c(19,19, 19, NA),
       col = c(rgb(0, 0, 1), rgb(0.5, 0, 1), rgb(1, 0.25, 0), rgb(1,0,0))
)

```

```{r, "Fig8"}

par(mfcol = c(1,2))
par(mar=c(4,4,0.5,0.5))
par(oma = c(0,0,0,0))

#CompareGSDs(cfdopA, cfdopB, 400, 400, alpha = 0.05)
#no signficant difference except for D70 and coarser

#CompareGSDs(cfdopA, cfdopB, 400, 400, alpha = 0.01)
#no signficant difference

plot(cfdopA$size, cfdopA$probs,
     type ="p",
     pch = 1,
     log = "x",
     col = "blue",
     ylim = c(0, 1),
     xlim = c(2,400),
     xlab = "grain size (mm)",
     ylab = "Proportion Finer"
     )
lines(cfdopA$size, cfdopA$probs, lty = 1, col = rgb(0,0,1))

lines(cfdopB$size, cfdopB$probs, lty = 1, col = rgb(1,0,0))
points(cfdopB$size, cfdopB$probs, pch = 19, col = rgb(1,0,0))
text(x = 300, y = 0.02, labels = "(a)")

plot(cfdopA$size, cfdopA$probs,
     type ="p",
     yaxt = "n",
     pch = 1,
     log = "x",
     col = "blue",
     ylim = c(0, 1),
     xlim = c(2,400),
     xlab = "grain size (mm)",
     ylab = " "
     )
polygon(polyopA,
        col=rgb(0, 0, 1,0.3),
        lty = 0)
#abline(h = c(0.05, 0.95), lty = 2)
#abline(v = c(16), lty = 1, col = rgb(1,0,0))

#lines(cfdbar$size, cfdbar$probs, lty = 1, col = rgb(1,0,0))
points(cfdopB$size, cfdopB$probs, pch = 19, col = rgb(1,0,0))
polygon(polyopB,
        col=rgb(1, 0, 0,0.3),
        lty = 0)
text(x = 300, y = 0.02, labels = "(b)")

legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c("Operator A", "Operator B"),
       lty = c(0,0),
       pch = c(1,19),
       col = c(rgb(0, 0, 1),rgb(1,0,0))
)

```

```{r, "errorAnalysis"}
CalcError = function(p, X, n= c(100,200,300,400,500,600,700, 800, 900, 1000)){
  tmp = rbind(WolmanCI(X,n[1],P = 100*p),
                    WolmanCI(X,n[2], P =100*p),
                    WolmanCI(X,n[3], P =100*p),
                    WolmanCI(X,n[4], P =100*p),
                    WolmanCI(X,n[5], P =100*p),
                    WolmanCI(X,n[6], P =100*p),
                    WolmanCI(X,n[7], P =100*p),
                    WolmanCI(X,n[8], P =100*p),
                    WolmanCI(X,n[9], P =100*p),
                    WolmanCI(X,n[10], P =100*p)
                    )
err = as.numeric(0.5*(tmp$upper - tmp$lower)/tmp$estimate)
return(err)
}

#function modified to calculate sorting index phi84 - phi16
CalcSDlog = function(X){
  tmp = WolmanCI(X, 100, P = c(16, 84))
  SDlog = diff(log2(tmp$estimate))
  return(SDlog)
}

srcs = c("C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "cfdopA", "cfdopB", "cfdpool", "cfdpool4", "cfdrun", "cfdrun4", "cfdbar", "cfdbar4", "k.surf", "cfd1hr", "cfd2hr", "cfd3hr", "cfd4hr", "cfd5hr", "cfd6hr", "cfd6hr", "cfd7hr", "cfd8hr", "G309A", "G309B")

Err50 = matrix(data=NA, nrow = 10 , ncol =  length(srcs)+1)
Err84 = matrix(data=NA, nrow = 10, ncol =  length(srcs)+1)
SDlog = numeric(length = length(srcs))

Err50[,1] = seq(100,1000,100)
Err84[,1] = Err50[,1]

for(i in seq_along(srcs)) {
  Err50[,i+1] = CalcError(0.5, get(srcs[i]))
  Err84[,i+1] = CalcError(0.84, get(srcs[i]))
  SDlog[i] = CalcSDlog(get(srcs[i]))
}

n100 = data.frame(med50 = NA)
n100$med50 = mean(( Err50[1,2:19]))
n100$min50 = min(( Err50[1,2:19]))
n100$max50 = max(( Err50[1,2:19]))
n100$med84 = mean(( Err84[1,2:19]))
n100$min84 = min(( Err84[1,2:19]))
n100$max84 = max(( Err84[1,2:19]))


n200 = data.frame(med50 = NA)
n200$med50 = mean(( Err50[2,2:19]))
n200$min50 = min(( Err50[2,2:19]))
n200$max50 = max(( Err50[2,2:19]))
n200$med84 = mean(( Err84[2,2:19]))
n200$min84 = min(( Err84[2,2:19]))
n200$max84 = max(( Err84[2,2:19]))

n500 = data.frame(med50 = NA)
n500$med50 = mean(( Err50[5,2:19]))
n500$min50 = min(( Err50[5,2:19]))
n500$max50 = max(( Err50[5,2:19]))
n500$med84 = mean(( Err84[5,2:19]))
n500$min84 = min(( Err84[5,2:19]))
n500$max84 = max(( Err84[5,2:19]))

```

```{r, "Fig9"}

par(mfcol = c(1,2))
par(mar=c(4,4,0.5,0.5))
par(oma = c(0,0,0,0))

#CompareGSDs(cfdheel, cfdframe, 400, 400, alpha = 0.05)
#no signficant difference except coarser than D70

#CompareGSDs(cfdheel, cfdframe, 400, 400, alpha = 0.01)
#no signficant difference excetp D75 to D90

plot(cfdheel$size, cfdheel$probs,
     type ="p",
     pch = 1,
     log = "x",
     col = "blue",
     ylim = c(0, 1),
     xlim = c(2,400),
     xlab = "grain size (mm)",
     ylab = "Proportion Finer"
     )
lines(cfdheel$size, cfdheel$probs, lty = 1, col = rgb(0,0,1))

lines(cfdframe$size, cfdframe$probs, lty = 1, col = rgb(1,0,0))
points(cfdframe$size, cfdframe$probs, pch = 19, col = rgb(1,0,0))
text(x = 300, y = 0.02, labels = "(a)")

plot(cfdheel$size, cfdheel$probs,
     type ="p",
     yaxt = "n",
     pch = 1,
     log = "x",
     col = "blue",
     ylim = c(0, 1),
     xlim = c(2,400),
     xlab = "grain size (mm)",
     ylab = " "
     )
polygon(polyheel,
        col=rgb(0, 0, 1,0.3),
        lty = 0)

points(cfdframe$size, cfdframe$probs, pch = 19, col = rgb(1,0,0))
polygon(polyframe,
        col=rgb(1, 0, 0,0.3),
        lty = 0)
text(x = 300, y = 0.02, labels = "(b)")

legend("topleft",
       inset = 0.02,
       cex = 0.75,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c("Heel-toe", "Sampling frame"),
       lty = c(0,0),
       pch = c(1,19),
       col = c(rgb(0, 0, 1),rgb(1,0,0))
)

```

```{r, "Fig10"}

par(mfcol = c(1,2))
par(mar=c(4,4,1,1))
par(oma = c(0,0,0,0))

matplot(Err50[,1], Err50[,2:19],
        type = "l",
        col = rgb(0,0,1, 0.3),
        lty = 1,
        lwd = 2,
        ylim = c(0, 0.6),
        xlim = c(100,1000),
        xlab = "sample size",
        ylab = expression(epsilon[50])
)
abline(v = c(200,500), lty = 1, lwd = 4, col = rgb(0,0,0,0.3))
text(x = 950, y = 0.0, labels = "(a)")

matplot(Err84[,1], Err84[,2:19],
        type = "l",
        col = rgb(0,0,1, 0.3),
        lty = 1,
        lwd = 2,
        ylim = c(0, 0.6),
        xlim = c(100,1000),
        xlab = "sample size",
        ylab = expression(epsilon[84])
)
abline(v = c(200,500), lty = 1, lwd = 4, col = rgb(0,0,0,0.3))
text(x = 950, y = 0.0, labels = "(b)")

```
```{r, fig11}
par(mfcol = c(1,2))
par(mar=c(4,4,1,1))
par(oma = c(0,0,0,0))

plot.cols = character(length = NSim)
mycolors = colorRampPalette(c("blue", "cyan", "yellow", "red"))(8)
filt = SErr50$si < 1.5
plot.cols[filt] = mycolors[1]
filt = SErr50$si >= 1.5 & SErr50$si < 2
plot.cols[filt] = mycolors[2]
filt = SErr50$si >= 2 & SErr50$si < 2.5
plot.cols[filt] = mycolors[3]
filt = SErr50$si >= 2.5 & SErr50$si < 3
plot.cols[filt] = mycolors[4]
filt = SErr50$si >= 3 & SErr50$si < 3.5
plot.cols[filt] = mycolors[5]
filt = SErr50$si >= 3.5 & SErr50$si < 4
plot.cols[filt] = mycolors[6]
filt = SErr50$si >= 4 & SErr50$si < 4.5
plot.cols[filt] = mycolors[7]
filt = SErr50$si >= 4.5 & SErr50$si < 5
plot.cols[filt] = mycolors[8]

plot(SErr50$N, SErr50$err,
     type = "p",
     pch = 20,
     cex = 0.75,
     col = plot.cols,
     ylim = c(0, 0.6),
     xlim=(c(0,1000)),
     xlab = "sample size",
      ylab = expression(epsilon[50])
     )

X = seq(0,1000,1)
Y1 = exp(powfit50$coefficients[1]+powfit50$coefficients[3]*1)*X^powfit50$coefficients[2]
Y2 = exp(powfit50$coefficients[1]+powfit50$coefficients[3]*5)*X^powfit50$coefficients[2]
lines(X,Y2, lwd = 2, col = "black" )
lines(X,Y1, lwd =2, col = "black", lty = 2 )
text(x = 950, y = 0.0, labels = "(a)")

legend("topright",
       inset = 0.02,
       cex = 0.8,
       bg = rgb(1,1,1),
       #box.lty = 0,
       legend = c(expression(4.0~phi),
                  expression(1.0~phi),
                  expression((1.0-1.5~phi)),
                  expression((1.5-2.0~phi)),
                  expression((2.0-2.5~phi)),
                  expression((2.5-3.0~phi)),
                  expression((3.0-3.5~phi)),
                  expression((3.5-4.0~phi)),
                  expression((4.0-4.5~phi)),
                  expression((4.5-5.0~phi))
                  ),
       lty = c(1,2,0,0,0,0,0,0,0,0),
       lwd = c(2,2,0,0,0,0,0,0,0,0),
       pch = c(NA,NA,20,20,20,20,20,20,20,20),
       col = c("black", "black", mycolors)
)

plot(SErr84$N, SErr84$err,
     type = "p",
     pch = 20,
     cex = 0.75,
     col = plot.cols,
     ylim = c(0, 0.6),
     xlim=(c(0,1000)),
     xlab = "sample size",
      ylab = expression(epsilon[84])
     )

X = seq(0,1000,1)
Y3 = exp(powfit84$coefficients[1]+powfit84$coefficients[3]*1)*X^powfit84$coefficients[2]
Y4 = exp(powfit84$coefficients[1]+powfit84$coefficients[3]*5)*X^powfit84$coefficients[2]
lines(X,Y4, lwd = 2, col = "black" )
lines(X,Y3, lwd = 2, col = "black", lty = 2 )
text(x = 950, y = 0.0, labels = "(b)")

Coef = c("A","B")
CoefTable = data.frame(Coef)
CoefTable$SD0.50 = c(coeff50[1] + coeff50[3]*1,
                     coeff84[1] + coeff84[3]*1)
CoefTable$SD0.75 = c(coeff50[1] + coeff50[3]*1.5,
                    coeff84[1] + coeff84[3]*1.5)
CoefTable$SD1.00 = c(coeff50[1] + coeff50[3]*2.0,
                    coeff84[1] + coeff84[3]*2.0)
CoefTable$SD1.25 = c(coeff50[1] + coeff50[3]*2.5,
                  coeff84[1] + coeff84[3]*2.5)
CoefTable$SD1.50 = c(coeff50[1] + coeff50[3]*3.0,
                  coeff84[1] + coeff84[3]*3.0)
CoefTable$SD1.75 = c(coeff50[1] + coeff50[3]*3.5,
                    coeff84[1] + coeff84[3]*3.5)
CoefTable$SD2.00 = c(coeff50[1] + coeff50[3]*4.0,
                  coeff84[1] + coeff84[3]*4.00)

```

```{r, "example"}
D50 = 0.055
Tstar = 0.045
S = 0.02
Tcrit = 9.81*1650*Tstar*D50
dcrit = Tcrit/(9810*S)
epsilon100 = exp(coeff50[1] + coeff50[3]*2.0)*100^coeff50[2]
D50low = 0.055*(1-epsilon100)
D50up = 0.055*(1+epsilon100)
Tcritlow = 9.81*1650*Tstar*D50low
dcritlow = Tcritlow/(9810*S)
Tcritup = 9.81*1650*Tstar*D50up
dcritup = Tcritup/(9810*S)

Q = 2.5
h = 0.23*Q^0.4
offset = h - dcrit
hfull = offset + 2*dcrit
Qfull = (hfull/0.23)^(1/0.4)
hlow = offset + 2*dcritlow
Qlow = (hlow/0.23)^(1/0.4)
hup = offset + 2*dcritup
Qup = (hup/0.23)^(1/0.4)

#<<FTreturn, echo = F>>=

# Code for plotting annual peak flow series on
# extreme-value (Gumbel) paper.
#
# This code illustrates how to customize graph axes, and
# also how to use superscripts in axis labels.
#
# RDM 2014 Feb 6
###############################################################

# Specify Fishtrap Creek peak flows for 1972 - 2011
Q = c(14, 3.77, 8.72, 12, 4.11, 6.03, 4.33, 3.31, 3.78, 9.64,
9.55, 9.27, 4.13, 11.7, 3.6, 5.85, 3.98, 3.88, 10.5, 6.01, 9.67,
10.8, 15.3, 10.1, 13.5, 5.05, 3.13, 8.68, 4.2, 6.3, 10.1, 8.8, 8.02,
8.08, 8.02, 7.9, 9.73)

# Set up x axis tick positions and labels
Ttick = c(1.001,1.01,1.1,1.5,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,25,30,35,40,45,50,60,70,80,90,100)

# Fit a line by method of moments, along with 95% confidence intervals
KTtick = -(sqrt(6)/pi)*(0.5772 + log(log(Ttick/(Ttick-1))))
QTtick = mean(Q) + KTtick*sd(Q)

RPlow = as.numeric(approx(x = QTtick, y = Ttick, xout = Qlow)[2])
RPup = as.numeric(approx(x = QTtick, y = Ttick, xout = Qup)[2])

epsilon500 = exp(coeff50[1] + coeff50[3]*2.0)*500^coeff50[2]
D50low2 = 0.055*(1-epsilon500)
D50up2 = 0.055*(1+epsilon500)
Tcritlow2 = 9.81*1650*Tstar*D50low2
dcritlow2 = Tcritlow2/(9810*S)
Tcritup2 = 9.81*1650*Tstar*D50up2
dcritup2 = Tcritup2/(9810*S)

hlow2 = offset + 2*dcritlow2
Qlow2 = (hlow2/0.23)^(1/0.4)
hup2 = offset + 2*dcritup2
Qup2 = (hup2/0.23)^(1/0.4)

RPlow2 = as.numeric(approx(x = QTtick, y = Ttick, xout = Qlow2)[2])
RPup2 = as.numeric(approx(x = QTtick, y = Ttick, xout = Qup2)[2])

```

